name: pce-2026
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy<2
  - pandas<3
  - matplotlib
  - seaborn
  - scikit-learn
  - shap
  - xgboost
  - scipy
  - polars
  - ipython
  - ipykernel
  - kagglehub
